USE [dbmSemanticAnalyticsSTG]
GO

IF  EXISTS (SELECT * FROM sys.sequences WHERE name = N'PatientID_seq')
BEGIN
drop SEQUENCE PatientID_seq
END

CREATE SEQUENCE [dbo].[PatientID_seq] 
 AS [int]
 START WITH 1
 INCREMENT BY 1
 MINVALUE -2147483648
 MAXVALUE 2147483647
 CACHE  2 
