
sqlcmd -S LOCALHOST\INST01 -E -C -d msdb -Q "EXEC msdb.dbo.sp_delete_job @job_name=N'ACG_Analytic_Reports', @delete_unused_schedule=1"
sqlcmd -S LOCALHOST\INST01 -E -C -d msdb -Q "EXEC msdb.dbo.sp_delete_job @job_name=N'ACG_Load_Report_Data', @delete_unused_schedule=1"
sqlcmd -S LOCALHOST\INST01 -E -C -d msdb -Q "EXEC msdb.dbo.sp_delete_job @job_name=N'ACG_Usage_Reports', @delete_unused_schedule=1"
sqlcmd -S LOCALHOST\INST01 -E -C -d msdb -Q "EXEC msdb.dbo.sp_delete_job @job_name=N'ClaimsForRegression', @delete_unused_schedule=1"
sqlcmd -S LOCALHOST\INST01 -E -C -d msdb -Q "EXEC msdb.dbo.sp_delete_job @job_name=N'PHA_Approved_Clusters', @delete_unused_schedule=1"
sqlcmd -S LOCALHOST\INST01 -E -C -d msdb -Q "EXEC msdb.dbo.sp_delete_job @job_name=N'PHA_Claims', @delete_unused_schedule=1"
sqlcmd -S LOCALHOST\INST01 -E -C -d msdb -Q "EXEC msdb.dbo.sp_delete_job @job_name=N'PHA_Claims_Onboarding', @delete_unused_schedule=1"
sqlcmd -S LOCALHOST\INST01 -E -C -d msdb -Q "EXEC msdb.dbo.sp_delete_job @job_name=N'PHA_DataRuleEditor', @delete_unused_schedule=1"
sqlcmd -S LOCALHOST\INST01 -E -C -d msdb -Q "EXEC msdb.dbo.sp_delete_job @job_name=N'PHA_DWH_Fact', @delete_unused_schedule=1"
sqlcmd -S LOCALHOST\INST01 -E -C -d msdb -Q "EXEC msdb.dbo.sp_delete_job @job_name=N'PHA_Main_Persist', @delete_unused_schedule=1"
sqlcmd -S LOCALHOST\INST01 -E -C -d msdb -Q "EXEC msdb.dbo.sp_delete_job @job_name=N'PHA_Monthly', @delete_unused_schedule=1"
sqlcmd -S LOCALHOST\INST01 -E -C -d msdb -Q "EXEC msdb.dbo.sp_delete_job @job_name=N'PHA_Prepare_Clustering', @delete_unused_schedule=1"
sqlcmd -S LOCALHOST\INST01 -E -C -d msdb -Q "EXEC msdb.dbo.sp_delete_job @job_name=N'PHA_Program_PatientAttribute', @delete_unused_schedule=1"
sqlcmd -S LOCALHOST\INST01 -E -C -d msdb -Q "EXEC msdb.dbo.sp_delete_job @job_name=N'PHA_RuleEditor', @delete_unused_schedule=1"
sqlcmd -S LOCALHOST\INST01 -E -C -d msdb -Q "EXEC msdb.dbo.sp_delete_job @job_name=N'PHA_Scheduler', @delete_unused_schedule=1"
sqlcmd -S LOCALHOST\INST01 -E -C -d msdb -Q "EXEC msdb.dbo.sp_delete_job @job_name=N'PHA_To_CAG', @delete_unused_schedule=1"
