sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGHospitalByCondition.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGHospitalByCondition.Table.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGMappingPatientEDC.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGMappingPatientEDC.Table.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGMappingPatientMEDC.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGMappingPatientMEDC.Table.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGMedicalMetrics.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGMedicalMetrics.Table.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGPatientMetrics.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGPatientMetrics.Table.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGReferenceEDC.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGReferenceEDC.Table.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGReferenceMEDC.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGReferenceMEDC.Table.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGReferencePatient.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGReferencePatient.Table.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGReferenceRUB.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGReferenceRUB.Table.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGSMRbyEDC.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\STG.ACGSMRbyEDC.Table.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.HospitalByCondition.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.HospitalByCondition.Table.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.MappingPatientEDC.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.MappingPatientEDC.Table.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.MappingPatientMEDC.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.MappingPatientMEDC.Table.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.MedicalMetrics.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.MedicalMetrics.Table.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.PatientMetrics.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.PatientMetrics.Table.sql.rpt
#sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.ReferenceEDC.Data.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.ReferenceEDC.Data.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.ReferenceEDC.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.ReferenceEDC.Table.sql.rpt
#sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.ReferenceMEDC.Data.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.ReferenceMEDC.Data.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.ReferenceMEDC.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.ReferenceMEDC.Table.sql.rpt
#sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.ReferencePatient.Data.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.ReferencePatient.Data.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.ReferencePatient.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.ReferencePatient.Table.sql.rpt
#sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.ReferenceRUB.Data.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.ReferenceRUB.Data.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.ReferenceRUB.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.ReferenceRUB.Table.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.SMRbyEDC.Table.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.SMRbyEDC.Table.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergeHospitalByCondition.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergeHospitalByCondition.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergeMappingPatientEDC.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergeMappingPatientEDC.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergeMappingPatientMEDC.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergeMappingPatientMEDC.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergeMedicalMetrics.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergeMedicalMetrics.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergePatientMetrics.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergePatientMetrics.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergeReferenceEDC.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergeReferenceEDC.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergeReferenceMEDC.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergeReferenceMEDC.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergeReferencePatient.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergeReferencePatient.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergeReferenceRUB.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergeReferenceRUB.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergeSMRbyEDC.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG.usp_MergeSMRbyEDC.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG_FK_HospitalByCondition_EDC_Code_ReferenceEDC_EDC_Code.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG_FK_HospitalByCondition_EDC_Code_ReferenceEDC_EDC_Code.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG_FK_MappingPatientEDC_EDC_Code_ReferenceEDC_EDC_Code.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG_FK_MappingPatientEDC_EDC_Code_ReferenceEDC_EDC_Code.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG_FK_MappingPatientEDC_patient_id_ReferencePatient_patient_id.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG_FK_MappingPatientEDC_patient_id_ReferencePatient_patient_id.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG_FK_MappingPatientMEDC_MEDC_Code_ReferenceMEDC_MEDC_Code.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG_FK_MappingPatientMEDC_MEDC_Code_ReferenceMEDC_MEDC_Code.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG_FK_MappingPatientMEDC_patient_id_ReferencePatient_patient_id.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG_FK_MappingPatientMEDC_patient_id_ReferencePatient_patient_id.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG_FK_MedicalMetrics_patient_id_ReferencePatient_patient_id.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG_FK_MedicalMetrics_patient_id_ReferencePatient_patient_id.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG_FK_PatientMetrics_patient_id_ReferencePatient_patient_id.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG_FK_PatientMetrics_patient_id_ReferencePatient_patient_id.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG_FK_PatientMetrics_resource_utilization_band_ReferenceRUB_RUB_Code.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG_FK_PatientMetrics_resource_utilization_band_ReferenceRUB_RUB_Code.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG_FK_SMRbyEDC_EDC_Code_ReferenceEDC_EDC_Code.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\ACG_FK_SMRbyEDC_EDC_Code_ReferenceEDC_EDC_Code.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGHospitalByCondition_v.View.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGHospitalByCondition_v.View.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGMappingPatientEDC_v.View.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGMappingPatientEDC_v.View.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGMappingPatientMEDC_v.View.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGMappingPatientMEDC_v.View.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGMedicalMetrics_v.View.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGMedicalMetrics_v.View.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGPatientMetrics_v.View.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGPatientMetrics_v.View.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGReferenceEDC_v.View.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGReferenceEDC_v.View.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGReferenceMEDC_v.View.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGReferenceMEDC_v.View.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGReferencePatient_v.View.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGReferencePatient_v.View.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGReferenceRUB_v.View.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGReferenceRUB_v.View.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGSMRbyEDC_v.View.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.ACGSMRbyEDC_v.View.sql.rpt
sqlcmd -S dbm8-data113\inst02 -i C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.MSTRConfiguration_v.View.sql -o C:\+\git\ral\ACG_SQL\ACG_SQL_18.1\Dim.MSTRConfiguration_v.View.sql.rpt
